### ISSUE TITLE
Argo CD - directory: recurse: true plugin bug 

### ISSUE THREAD

**Issue by JoshDanielWalker** [IBM/argocd-vault-plugin#103]
**Describe the bug**
When adding the plugin to Argo cd Application YAML if directory, recurse is set to true like below an error is given. 
`directory:
      recurse: true`
      
`multiple application sources defined: Directory,Plugin`

**Comment by werne2j** [comment]
This error is because you are trying to define multiple plugins. You would need to remove `directory: recurse: true`. Or only use `Directory` this is not an issue with the plugin but how ArgoCD works as it only allows one "application source" at a time

**Comment by JoshDanielWalker** [comment]
Thank you for your quick reply.
ok, I thought this might be an issue with Argo cd plugins in general.

**Comment by JoshDanielWalker** [comment]
Removing directory: worked however, the templating syntax for the plugin picked up on some prometheus alert yaml.

 "< +Inf ) >".

eg `((( sum(container_memory_usage_bytes{image!="",container!="POD", namespace!="kube-system"}) by (container,pod,namespace)  / sum(container_spec_memory_limit_bytes{image!="",container!="POD",namespace!="kube-system"}) by (container,pod,namespace) ) * 100 ) < +Inf ) > 75`

**Comment by JoshDanielWalker** [comment]
If there is whitespace could the plugin ignore the < > ignore?

**Comment by jkayani** [comment]
@JoshDanielWalker Alternatively, what if we just an annotation to the YAML to tell AVP to skip it, something like `avp_ignore: True`?

**Comment by JoshDanielWalker** [comment]
@jkayani definitely, this would help and would stop Argo from getting stuck in our case. 
I don't think whitespace should be included in the templating personally but I understand it is more complex to add this change?

**Comment by jkayani** [comment]
> I don't think whitespace should be included in the templating personally but I understand it is more complex to add this change?

You're probably right, it should not. I think we can try adding a fix for that too - should just be a matter of changing the regex. But the annotation would be the proper way to tell AVP to ignore a file since that will work regardless of what the strings in your YAML look like

**Comment by jkayani** [comment]
@JoshDanielWalker It's not particularly complex at all - it's just changing the regexp we use to recognize `<placeholder>`'s. 

However, I talked it over with @werne2j and we decided to omit adding that change in behavior because it'd be a big breaking change and the `avp_ignore` annotation is sufficient to address this use-case.

**Comment by jkayani** [comment]
@JoshDanielWalker This is fixed in https://github.com/IBM/argocd-vault-plugin/releases/tag/v0.7.0, so you can install that version of AVP and add the `avp_ignore: true` annotation to your PD alert YAMLs

**Comment by JoshDanielWalker** [comment]
@jkayani ok great thank you, I will roll this change out and test the `avp_ignore: true` annotation.
Thank you
