### ISSUE TITLE
Vault invalid role name

### ISSUE THREAD

**Issue by MuhammadJamee** [IBM/argocd-vault-plugin#107]
![image](https://user-images.githubusercontent.com/40118805/112726858-55cbd500-8f41-11eb-9c27-6391db33e69c.png)

**Comment by werne2j** [comment]
That appears to be an issue with the role you are using for the Kubernetes auth. 

What version of the plugin are you using? 

Can you provide more details about the role being used?

**Comment by werne2j** [comment]
Also, please input a better issue title for others who may be searching for help

**Comment by MuhammadJamee** [comment]
So I deploy argocd and then (vault using helm) then unsealed the vault.

**argocd-vault-plugin version: v0.7.0.**

- Used this as a service  account: 

apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd
  namespace: argocd


- Updated my argocd-repo-server with this:

kind: Deployment
apiVersion: apps/v1
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      serviceAccount: argocd
      automountServiceAccountToken: true
---

containers:
- name: argocd-repo-server
  volumeMounts:
  - name: custom-tools
    mountPath: /usr/local/bin/argocd-vault-plugin
    subPath: argocd-vault-plugin
  envFrom:
    - secretRef:
        name: argocd-vault-plugin-credentials
volumes:
- name: custom-tools
  emptyDir: {}
initContainers:
- name: download-tools
  image: alpine:3.8
  command: [sh, -c]
  args:
    - wget -O argocd-vault-plugin
      https://github.com/IBM/argocd-vault-plugin/releases/download/v0.7.0/argocd-vault-plugin_0.7.0_linux_amd64

      chmod +x argocd-vault-plugin && mv argocd-vault-plugin /custom-tools/
  volumeMounts:
    - mountPath: /custom-tools
      name: custom-tools


- Vault configuration:
 
command: kubectl exec --stdin=true --tty=true vault-0 -- /bin/sh 
#helped me get inside my vault pod

command: vault login 

command: vault auth enable Kubernetes

command: vault write auth/kubernetes/config \
    token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
    kubernetes_host=https://35.225.216.255 \
    kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt

https://35.225.216.255 #cluster-ip 

command: vault write auth/kubernetes/role/argocd \
    bound_service_account_names=argocd \
    bound_service_account_namespaces=argocd \
    policies=argocd \
    ttl=1h


kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
data:
  AVP_VAULT_ADDR: http://vault:8200 #aHR0cDovL3ZhdWx0OjgyMDA=   
  AVP_TYPE: vault #dmF1bHQ=
  AVP_AUTH_TYPE: k8s #azhz
  AVP_K8S_ROLE: argocd #YXJnb2Nk 

I used (echo -n "example" | base64 ) to encode all the stuff inside the "data" portion.

###############################
Then I deployed this
###############################

kubectl apply -f - <<EOF
apiVersion: v1
data:
  VAULT_ADDR: aHR0cDovL3ZhdWx0OjgyMDA= 
  AUTH_TYPE: azhz
  TYPE: dmF1bHQ=
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque
EOF

###############################

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: argocd
    namespace: argocd

##############################
also, this command mentions in the article isn't working: vault write avp/test sample=secret (screenshot is attached)
article: https://itnext.io/argocd-secret-management-with-argocd-vault-plugin-539f104aff05

This is the series of commands and deployment I used and end up seeing the error I posted on. please let me know what I'm missing. Thank you!

![image](https://user-images.githubusercontent.com/40118805/112736682-592d8380-8f76-11eb-9247-0924c9e78c9c.png)

**Comment by werne2j** [comment]
@MuhammadJamee I am unable to recreate your issue. After doing some research it appears that error comes from Vaults lack of ability to find the role you are trying to use. https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/9b38be8f9574147ff397c0dc0233c425c64eb6f8/path_login.go#L78

If you look at this issue https://github.com/IBM/argocd-vault-plugin/issues/102 you can see how they were able to get it to work by using the default service account in the argocd namespace. Hope that helps.

As far as your second comment.. The reason that doesnt work is because you do not have a vault path setup at `avp`. I should have been more clear about that. You would have to do `vault secrets enable -version=1 avp` to be able to use that path.

**Comment by MuhammadJamee** [comment]
> @MuhammadJamee I am unable to recreate your issue. After doing some research it appears that error comes from Vaults lack of ability to find the role you are trying to use. https://github.com/hashicorp/vault-plugin-auth-kubernetes/blob/9b38be8f9574147ff397c0dc0233c425c64eb6f8/path_login.go#L78
> 
> If you look at this issue #102 you can see how they were able to get it to work by using the default service account in the argocd namespace. Hope that helps.
> 
> As far as your second comment.. The reason that doesnt work is because you do not have a vault path setup at `avp`. I should have been more clear about that. You would have to do `vault secrets enable -version=1 avp` to be able to use that path.

vault secrets enable -path=avp kv-v1 ** (this is working command)

**Comment by MuhammadJamee** [comment]
After updating the stuff mentioned, I'm receiving a different message now.
Also,

kind: Secret
apiVersion: v1
metadata:
name: argocd-vault-plugin-credentials
namespace: argocd
type: Opaque
data:
VAULT_ADDR: http://vault:8200 #aHR0cDovL3ZhdWx0OjgyMDA=
TYPE: vault #dmF1bHQ=
AUTH_TYPE: k8s #azhz
K8S_ROLE: argocd #YXJnb2Nk
#Error changed due to the removal of "AVP_"

![image](https://user-images.githubusercontent.com/40118805/112747326-21522a80-8fce-11eb-8460-1d5905227fef.png)

**Comment by werne2j** [comment]
@MuhammadJamee you need the AVP prefix if you are mounting a secret as an Env Var. How are you calling the plugin in the configManagement section of the argocd config map?

**Comment by MuhammadJamee** [comment]
Ok, I'll put AVP_ prefix back in secret/

####################
This is my **configMap** 

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  configManagementPlugins: |
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]

**Comment by MuhammadJamee** [comment]
This is something new, I think I'm very close to getting it to work.
![image](https://user-images.githubusercontent.com/40118805/112757493-588efe80-9003-11eb-8672-e9faf57621ad.png)

**Comment by werne2j** [comment]
@MuhammadJamee My guess would be that your vault kubernetes role does not have the correct access to read from the avp secret path

**Comment by MuhammadJamee** [comment]
> @MuhammadJamee My guess would be that your vault kubernetes role does not have the correct access to read from the avp secret path

Yes, I have figured it out. but after it, I'm unable to sync your demo code. SS attached. Let me know if you can help me with this as well. 
![image](https://user-images.githubusercontent.com/40118805/112764038-50918780-9020-11eb-876f-311c5147d4d1.png)

**Comment by werne2j** [comment]
What is the error?

**Comment by MuhammadJamee** [comment]
My argocd application: 

https://github.com/werne2j/arogcd-vault-plugin-demo/blob/main/example-secret.yaml

it is unable to fetch or sync

![image](https://user-images.githubusercontent.com/40118805/112764971-55583a80-9024-11eb-9857-9d9148be4f54.png)

**Comment by MuhammadJamee** [comment]
Also, with this secret do we need to put AVP_ prefix? 

apiVersion: v1
data:
  VAULT_ADDR: Zm9v
  AUTH_TYPE: Zm9v
  GITHUB_TOKEN: Zm9v
  TYPE: Zm9v
kind: Secret
metadata:
  **name: vault-configuration**
  namespace: argocd
type: Opaque

**Comment by werne2j** [comment]
That secret is not needed. The only one needed is the one you mounted to the repo server.

How did you load data the vault?

**Comment by werne2j** [comment]
You sent the events, i would need to see the actual argocd errors.

**Comment by MuhammadJamee** [comment]
> That secret is not needed. The only one needed is the one you mounted to the repo server.
> 
> How did you load data the vault?

- deployed vault using help.
- kubectl exec --stdin=true --tty=true vault-0 -- /bin/sh #helped me get inside my vault pod
- vault login 
- vault auth enable kubernetes
- vault write auth/kubernetes/config \
    token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
    kubernetes_host=https://(kubectl cluster-info) \
    kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt

- vault write auth/kubernetes/role/argocd \
    bound_service_account_names=default \
    bound_service_account_namespaces=argocd \
    policies=argocd \
    ttl=1h

- vault secrets enable -path=avp kv-v2
- vault policy write argocd - <<EOF
path "avp/test" {
  capabilities = ["read"]
}
EOF

- vault kv put avp/data/test sample=secret
- vault kv get avp/data/test

This is how I loaded my vault. (I could use UI but this is Ok for me)

**Comment by werne2j** [comment]
I think what was happening is you have a string in Vault but the yaml file in the example repo was expecting a base64 string. I updated the yaml to accept plain text. So hopefully that will work now after a sync. (Many things have changed since that article has been published)

**Comment by MuhammadJamee** [comment]
it's working. Thank you
