### ISSUE TITLE
Update annotations to be an appropriate format

### ISSUE THREAD

**Issue by werne2j** [IBM/argocd-vault-plugin#112]
We should migrate our annotations such as `avp_path` to follow the kubernetes pattern of something like `kubernetes.io/somthing/avp_path`.

**Comment by werne2j** [comment]
proposed
```
avp.kubernetes.io/path 
avp.kubernetes.io/ignore 
avp.kubernetes.io/kv-version
```

**Comment by jkayani** [comment]
Those names look good to me
