### ISSUE TITLE
Read templates from stdin

### ISSUE THREAD

**Issue by jkayani** [IBM/argocd-vault-plugin#116]
**Is your feature request related to a problem? Please describe.**

It'd be nice for AVP to read YAMLs from stdin directly, rather than expecting a path on the filesystem. 

**Describe the solution you'd like**
Something like:

```
argocd-vault-plugin generate - < my-template.yaml
```

where `-` is the path argument to tell AVP read from stdin

**Describe alternatives you've considered**

- Piping to an external file and then using that one works just fine

**Additional context**
See integrations of AVP with other YAML generators; i.e, Helm, Kustomize

**Comment by jhoover4** [comment]
@werne2j I'd be happy to take a crack at this if you need help

**Comment by werne2j** [comment]
@jhoover4 sure! I will assign the issue to you
