### ISSUE TITLE
AVP_VAULT_SKIP_VERIFY doesn't appear to be recognised when logging into AppRole in Vault with Self-Signed/Untrusted Certs

### ISSUE THREAD

**Issue by jaegerbane** [IBM/argocd-vault-plugin#118]
**Describe the bug**
When following the guide in https://itnext.io/argocd-secret-management-with-argocd-vault-plugin-539f104aff05 , using a Vault that is running self-signed or untrusted certs, you see the following error message when attempting to deploy an app:

time="2021-04-30T15:23:59Z" level=error msg="`argocd-vault-plugin generate ./` failed exit status 1: Error: Put \"https://vault url/v1/auth/approle/login\": x509: certificate signed by unknown authority

...where vault url is the value provided under AVP_VAULT_ADDR.

According to the README, the argocd vault plugin provides support for the VAULT_SKIP_VERIFY Env variable to skip this checking stage (listed under AVP_VAULT_SKIP_VERIFY). 

Setting it to true and ensuring that it is registered inside the argocd pod as described in the tutorial however, has no effect on the deploy attempt. The same error results as if it wasn't present. Manual testing of the PUT mentioned above without --insecure replicates the effect.

**To Reproduce**
1. Target a Vault running self signed certs.
2. Repeat the steps of linked tutorial
3. Attempt deploy sample-secret application listed here: https://github.com/werne2j/arogcd-vault-plugin-demo
4. Error message is output via both ArgoCD UI and pod logs

**Expected behavior**
Sample-secret application should progress to the deploy stage with no further X509 issues.

**Additional context**
I double checked that the Env var made it into the ArgoCD pod via the secret injection laid out in the tutorial, it did indeed make it in there, along with everything else from the Vault credentials:

AVP_VAULT_SKIP_VERIFY=true

**Comment by werne2j** [comment]
@jaegerbane what version of the plugin are you using?

**Comment by jaegerbane** [comment]
@werne2j that might be it - I was following the tutorial linked above and looking at the wget, it looks like its fetching v.0.3.0. Judging from the tags on the repo, that's pretty old I'll retry with the latest stable version.

**Comment by jaegerbane** [comment]
Pulled tag v0.7.0 and loaded it in using the same approach - no difference to output. Still complaining about certificate signed by unknown authority, when set to skip verify.

**Comment by werne2j** [comment]
Release https://github.com/IBM/argocd-vault-plugin/releases/tag/v0.5.0 should give the ability to use skip verify. Make sure in your repo-server pod that you are actually using 0.7.0

**Comment by jaegerbane** [comment]
This is the output I get from inside the ArgoCD repo-server pod, running the plugin via the CMD:

$ argocd-vault-plugin version
v0.7.0

**Comment by werne2j** [comment]
@jaegerbane i was unable to replicate your issue on `0.7.0`
```
project: default
source:
  repoURL: 'https://github.com/werne2j/argocd-example'
  path: test
  targetRevision: HEAD
  plugin:
    name: argocd-vault-plugin
destination:
  server: 'https://kubernetes.default.svc'
  namespace: mynamespace
```
My Environment Variables:
<img width="260" alt="Screen Shot 2021-05-04 at 1 43 29 PM" src="https://user-images.githubusercontent.com/5973248/117046509-c56e7600-acde-11eb-975e-189bec1f97e7.png">

Synced App:
<img width="728" alt="Screen Shot 2021-05-04 at 1 43 41 PM" src="https://user-images.githubusercontent.com/5973248/117046512-c56e7600-acde-11eb-80fd-6b205a4b6d34.png">

And with `AVP_VAULT_SKIP_VERIFY` set to false i get `Put "https://vault.vault-namespace:8200/v1/auth/approle/login": x509: certificate signed by unknown authority`

**Comment by werne2j** [comment]
Closing this issue with lack of activity

**Comment by o-grigorev** [comment]
My 5 cents here. The actual variable name is 
`VAULT_SKIP_VERIFY` not `AVP_VAULT_SKIP_VERIFY`
https://github.com/argoproj-labs/argocd-vault-plugin/blob/9f8f17e518a50651804f5b5cdb1c77a14591dccd/cmd/generate_test.go#L26
