### ISSUE TITLE
AppRole auth against Vault - mechanism to rotate secretID that expires after a period of time

### ISSUE THREAD

**Issue by clcchai** [IBM/argocd-vault-plugin#126]
**Is your feature request related to a problem? Please describe.**
ArgoCD vault Plugin supports approle Auth against Vault.  However, the secretID once expires, currently there is no clear way of process to rotate the secretID as per below that is stored as kube secret

https://www.vaultproject.io/docs/auth/approle#secretid
SecretID has a TTL or expiry

> VAULT_ADDR: Your HashiCorp Vault Address
> AVP_TYPE: vault
> AVP_AUTH_TYPE: approle
> AVP_ROLE_ID: Your AppRole Role ID
> AVP_SECRET_ID: Your AppRole Secret ID

**Describe the solution you'd like**
have a mechanism to refresh SecretID against vault

**Describe alternatives you've considered**

**Additional context**

**Comment by werne2j** [comment]
@clcchai currently the way is to just update the secret with the new secret id. We are open to hearing any proposals and we can ideate on this ourself. But we don’t have anything in the backlog for this at the moment

**Comment by arunbagul** [comment]
Hi Team,

I'm also facing this issue, how to rotate secret id for given roleid

Regards,
Arun

**Comment by werne2j** [comment]
@arunbagul as stated above, that is not something we plan to build into the plugin and expect you to rotate your secret id outside of the plugin. If you have a proposal we are open to listening! 🙂
