### ISSUE TITLE
Running script locally gets error `line 1: Not: command not found`.

### ISSUE THREAD

**Issue by jhoover4** [IBM/argocd-vault-plugin#128]
**Describe the bug**

Running the script locally I keep getting `line 1: Not: command not found`.

```
~ argocd-vault-plugin generate test.txt
/usr/local/bin/argocd-vault-plugin: line 1: Not: command not found
```

**To Reproduce**
1. Download the plugin v 1.0.0 `curl -L -o argocd-vault-plugin https://github.com/IBM/argocd-vault-plugin/releases/download/1.0.0/argocd-vault-plugin_1.0.0_darwin_amd64`
2. Set env variables for approle authentication
3. Run script on test file `argocd-vault-plugin generate test.txt`

**Expected behavior**
Script to generate vault secrets as expected

**Additional context**
Operating system

```
~ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.6
BuildVersion:	18G9216
```

**Comment by werne2j** [comment]
@jhoover4 You would need to move or copy the binary to `/usr/local/bin` or do `./argocd-vault-plugin generate test.txt`

**Comment by jhoover4** [comment]
Ah sorry I didnt specify that. I did the rest of the steps in the `README` as well.

```
~ chmod +x argocd-vault-plugin
~ mv argocd-vault-plugin /usr/local/bin
```

I downloaded the git repo and built the Go binary myself, which is now working as expected. I wonder if I'm downloading the wrong binary for myself?

**Comment by jhoover4** [comment]
Unfortunately still having a problem with this. This is the Make recipe I'm running:

```
ARGO_VAULT_VER = 1.0.0
OPERATING_SYSTEM = darwin

.PHONY: install-argo-vault-plugin
install-argo-vault-plugin:
	@if [ ! command -v argocd-vault-plugin &> /dev/null ]; then \
		curl -L -o argocd-vault-plugin https://github.com/IBM/argocd-vault-plugin/releases/download/$(ARGO_VAULT_VER)/argocd-vault-plugin_$(ARGO_VAULT_VER)_$(OPERATING_SYSTEM)_amd64 && \
		chmod +x argocd-vault-plugin && \
		mv argocd-vault-plugin /usr/local/bin; \
	fi
```

**Comment by werne2j** [comment]
I think your curl might be wrong, you have `https://github.com/IBM/argocd-vault-plugin/releases/download/1.0.0/argocd-vault-plugin_1.0.0_darwin_amd64` but you need `https://github.com/IBM/argocd-vault-plugin/releases/download/v1.0.0/argocd-vault-plugin_1.0.0_darwin_amd64` notice the `v` before `1.0.0` after download

**Comment by jhoover4** [comment]
Ugh so it goes before the directory version but not in the file url 🤦, my bad thanks man.
