### ISSUE TITLE
docs: AVP_AUTH_TYPE should mention k8s auth

### ISSUE THREAD

**Issue by teejaded** [IBM/argocd-vault-plugin#131]
**Describe the bug**
It would be helpful if the full-list-of-supported-parameters mentioned `k8s` is valid value for `AVP_AUTH_TYPE`

https://github.com/IBM/argocd-vault-plugin/blob/main/README.md#full-list-of-supported-parameters

**Comment by werne2j** [comment]
@teejaded good catch, will update the docs soon
