### ISSUE TITLE
docs: add link to helm-wrap

### ISSUE THREAD

**Issue by teejaded** [IBM/argocd-vault-plugin#136]
**Is your feature request related to a problem? Please describe.**

Do you guys think the community would appreciate a link to my project with documentation on how to use it with argocd-vault-plugin?

https://github.com/teejaded/helm-wrap/

It allows you to use an ArgoCD Helm Application CRD with argocd-vault-plugin.

**Describe the solution you'd like**

Add a short mention that helm-wrap is another alternative to an ArgoCD custom plugin.   
Link to documentation for using helm-wrap with argocd-vault-plugin.

**Describe alternatives you've considered**

Don't document helm-wrap.

**Additional context**

Our team uses ArgoCD Applications with the helm syntax quite a bit.  I've always disliked losing access to all of the helm features when switching to custom plugins. This is why I created a tool which lets you pre/post process helm yaml.

**Comment by werne2j** [comment]
@teejaded We appreciate the contributions but i dont think your project would really fit into the docs anywhere. So i will close this issue for now. Thanks again!
