### ISSUE TITLE
Authentication for AWS secret manager via IAM roles

### ISSUE THREAD

**Issue by fvdnabee** [IBM/argocd-vault-plugin#148]
It is my understanding that currently support for authentication when using the AWS Secrets Manager as a back end is limited to just the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables (at least this is what is documented). 

For pods running on an AWS k8s cluster (EKS), it is possible to authenticate with AWS using IAM roles via [IRSA](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html). As documented [here](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html#pod-configuration), EKS sets the following environment variables for pods configured to employ IRSA: `AWS_ROLE_ARN` and `AWS_WEB_IDENTITY_TOKEN_FILE`. One nice thing about IRSA is that you only need to add a single annotation to the serviceaccount that runs your pod (if you have setup the IAM roles), there is no need to fiddle with access keys.

Would it be possible to authenticate with AWS from the argocd-vault-plugin via IAM/IRSA? Could it be that IAM auth is already available, as the plugin relies on the aws go SDK for authentication? I've been unable to test this.

**Comment by werne2j** [comment]
Hi @fvdnabee as of right now, `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are required. We don't have anything on the roadmap for adding any other AWS auth methods right now. 

However, we are accepting pull requests if you want suggest a change! It would be nice to nativly be able to accept all aws auth methods, so it might be as simple as removing the checks around the id and secret for the `awssecretsmanager` type.

**Comment by fvdnabee** [comment]
@werne2j from my testing it appears that removing https://github.com/IBM/argocd-vault-plugin/blob/main/pkg/config/config.go#L112 is sufficient indeed. The SDK will try a chain of auth method: see https://github.com/aws/aws-sdk-go#configuring-credentials It does appear wise to ensure the proper region is set, currently the code expects an env variable to be present to set the region (default to `us-east-2` if it absent). However, I'm not sure whether this is the recommended method of setting the region; as e.g. the shared credentials file can also specify the region.

I'll do some further testing and try to submit a PR later today.

**Comment by fvdnabee** [comment]
Closed with merging #151
