### ISSUE TITLE
AWS SM backend: unclear that default region is used.

### ISSUE THREAD

**Issue by fvdnabee** [IBM/argocd-vault-plugin#154]
**Is your feature request related to a problem? Please describe.**
With the awssecretsmanager backend, when the user forgets to specify an `AWS_REGION`, the default region (i.e. us-east-2) is used which results in `ResourceNotFoundException: Secrets Manager can't find the specified secret.` if the secret is not in the default region. A user might waste some time figuring out that this was due to `AWS_REGION` not being set.

**Describe the solution you'd like**
Issue a warning to inform the user that (s)he forget to set `AWS_REGION` and that the default region will be used. I'm submitting a PR for this momentarily.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by werne2j** [comment]
We do have some documentation on the default region https://github.com/IBM/argocd-vault-plugin#aws-authentication but a message from the tool cant hurt

**Comment by werne2j** [comment]
Will look to release as part of v1.2.0
