### ISSUE TITLE
Add support for other secret management tools

### ISSUE THREAD

**Issue by werne2j** [IBM/argocd-vault-plugin#159]
Currently we support HashiCorp Vault, IBM Secrets Manager and AWS Secrets Manager as backends. We should look into any other secret management tools that we can add support for. GCP Secrets Manager and Azure Key Vault are two candidates

**Comment by werne2j** [comment]
Adds GCP Secret Manager https://github.com/IBM/argocd-vault-plugin/pull/183

**Comment by jkayani** [comment]
GCP SM available in https://github.com/IBM/argocd-vault-plugin/releases/tag/v1.3.0

**Comment by werne2j** [comment]
We can close this now. As we also have Azure in an open PR
