### ISSUE TITLE
Placeholder replacement - replaces the whole value of the key. Not only placeholder.

### ISSUE THREAD

**Issue by rimasgo** [IBM/argocd-vault-plugin#162]
Hello!

**Is your feature request related to a problem? Please describe.**
I am trying to configure alert-manager (Prometheus) on Openshift V4 cluster and the configuration for it is not very GitOps friendly (https://prometheus.io/docs/alerting/latest/configuration/). At first glance it looks okay however the essentially it's a huge HELM values file and it has a password (smtp_user_password) hence it has to be created as a secret.

I have come up with a way of creating it with named templates (helm) however the place holders overrides the whole value of the key and also only the last place holder is picked up.

This is how my secret YAML looks before running generate with Vault plugin (edited)

apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: openshift-monitoring
  annotations:
    avp.kubernetes.io/path: "secret/data/namespace/alertmanager"
data:
  alertmanager.yaml: CiJnbG9iYWwiOgogICJyZXNvbHZlX3RpbWVvdXQiOiAiNW0iCiAgCiAgInNtdHBfZnJvbSI6ICJlbWFpbEBlbWFpbC5jb20iCiAgInNtdHBfc21hcnRob3N0IjogInNtdHAtcmVsYXkuZG9tYWluLm5hbWU6MjUiCiAgInNtdHBfYXV0aF91c2VybmFtZSI6<username | base64encode>CiAgInNtdHBfYXV0aF9wYXNzd29yZCI6<password | base64encode>CiJyZWNlaXZlcnMiOgotICJuYW1lIjogImJjcF9tYWlsX2FsZXJ0IgogICJlbWFpbF9jb25maWdzIjoKICAtICJ0byI6ICJlbWFpbEBlbWFpbC5jb20iCiAgICAidGxzX2NvbmZpZyI6CiAgICAgICAiaW5zZWN1cmVfc2tpcF92ZXJpZnkiOiB0cnVlCi0gIm5hbWUiOiAibWFpbF9hbmRfbmV0Y29vbF9hbGVydCIKICAiZW1haWxfY29uZmlncyI6CiAgLSAidG8iOiAiZW1haWxAZW1haWwuY29tIgogICAgInRsc19jb25maWciOgogICAgICAgImluc2VjdXJlX3NraXBfdmVyaWZ5IjogdHJ1ZQogICJ3ZWJob29rX2NvbmZpZ3MiOgogIC0gInVybCI6ICJodHRwOi8vbmV0Y29vbC1pbnRlZ3JhdG9yLm9wZW5zaGlmdC1pbmZyYS5zdmMuY2x1c3Rlci5sb2NhbDo4MDgwL3dlYmhvb2siCiAgICAic2VuZF9yZXNvbHZlZCI6IHRydWUKLSAibmFtZSI6ICJudWxsIg==
type: Opaque

What happens is that it argocd-vault-plugin removes all the existing data in the value and replaces only last placeholder. I know this is an edge case but I was expecting that it replaces the placeholders only and keeps all hardcoded strings as is (
https://github.com/IBM/argocd-vault-plugin/blob/main/pkg/kube/template.go#L56 )

**Describe the solution you'd like**
I would like that it vault-plugin would replace the placeholders in the YAML object and leave the remaining data in the file as is. Something like Match-and-Replace only the placeholder part. 

**Describe alternatives you've considered**
I have spent quite a lot of time on this but can't figure any way forward. Putting whole file in the secret is not an option as there are some data in the configuration file which has to be changed.

**Additional context**
I might not have thought of everything or I am using something not right. Please let me know if you think I could approach this problem in a different way.

**Comment by werne2j** [comment]
@rimasgo I see the issue. It appears that the `base64encode` modifier is the problem. If you can base64 the username and password when loading into vault and then reference them like:

```
CiJnbG9iYWwiOgogICJyZXNvbHZlX3RpbWVvdXQiOiAiNW0iCiAgCiAgInNtdHBfZnJvbSI6ICJlbWFpbEBlbWFpbC5jb20iCiAgInNtdHBfc21hcnRob3N0IjogInNtdHAtcmVsYXkuZG9tYWluLm5hbWU6MjUiCiAgInNtdHBfYXV0aF91c2VybmFtZSI6<username>CiAgInNtdHBfYXV0aF9wYXNzd29yZCI6<password>CiJyZWNlaXZlcnMiOgotICJuYW1lIjogImJjcF9tYWlsX2FsZXJ0IgogICJlbWFpbF9jb25maWdzIjoKICAtICJ0byI6ICJlbWFpbEBlbWFpbC5jb20iCiAgICAidGxzX2NvbmZpZyI6CiAgICAgICAiaW5zZWN1cmVfc2tpcF92ZXJpZnkiOiB0cnVlCi0gIm5hbWUiOiAibWFpbF9hbmRfbmV0Y29vbF9hbGVydCIKICAiZW1haWxfY29uZmlncyI6CiAgLSAidG8iOiAiZW1haWxAZW1haWwuY29tIgogICAgInRsc19jb25maWciOgogICAgICAgImluc2VjdXJlX3NraXBfdmVyaWZ5IjogdHJ1ZQogICJ3ZWJob29rX2NvbmZpZ3MiOgogIC0gInVybCI6ICJodHRwOi8vbmV0Y29vbC1pbnRlZ3JhdG9yLm9wZW5zaGlmdC1pbmZyYS5zdmMuY2x1c3Rlci5sb2NhbDo4MDgwL3dlYmhvb2siCiAgICAic2VuZF9yZXNvbHZlZCI6IHRydWUKLSAibmFtZSI6ICJudWxsIg==
```

That should work as a work around

**Comment by rimasgo** [comment]
@werne2j , thanks for response. Will try it today. I can see you have opened I ticked for it - thanks!

**Comment by rimasgo** [comment]
Tested the suggested method. It worked fine! Just have base64 encoding problems with kube api now but that's not related. 

Thanks for your help!

**Comment by werne2j** [comment]
This was released via https://github.com/IBM/argocd-vault-plugin/releases/tag/v1.1.3
