### ISSUE TITLE
Don't take the last version of vault secret

### ISSUE THREAD

**Issue by obeyler** [IBM/argocd-vault-plugin#173]
**Describe the bug**
Il I create a new version of a secret, the argocd-vault-plugin doesn't care about it even if I try to synchronize argo application.
To be able to take the last version of a vault secret I need to delete argocd pods

**To Reproduce**
1. Create a new version of a vault kv (v2)  secrets
2. Click on argocd synchronize
3. the deployment still contain old value

**Expected behavior**
when synchronize an application the last version of a secret should always be taken

**Comment by werne2j** [comment]
@obeyler if you do a “hard refresh” your secrets should go out of sync and then a sync will bring in the new value from Vault

**Comment by obeyler** [comment]
Thanks @werne2j Good tips !

**Comment by rshiva777** [comment]
@obeyler @werne2j ,

Could you please let me know why argocd is unable to pick the newer/updated secret from vault although auto sync is enabled.

FYI, doing hardrefresh manually from argocd UI make it work, but i want this to be in a automated fashion where argocd read secret from vault whenever vault secret gets updated

**Comment by werne2j** [comment]
@rshiva777 

> Could you please let me know why argocd is unable to pick the newer/updated secret from vault although auto sync is enabled.

This is a question for https://github.com/argoproj/argo-cd we are just a binary that Argo CD executes during sync.
