### ISSUE TITLE
Vault updated secret does not update on Cluster

### ISSUE THREAD

**Issue by pbmoses** [IBM/argocd-vault-plugin#174]
**Describe the bug**
If a vault secret is updated, the secret does not seem to update on the cluster, even when the secret has been removed from cluster then re-sync. 
**To Reproduce**
1. create secret in vault
2. sync secret. 
3. change secret in vault, keeping the secret manifest the same
4. remove secret from cluster then re-sync
5. secret populates with the original data from vault

**Expected behavior**
updated secret would sync

**Additional context**
Possibly this is a question more than a bug, testing was with a simple opaque KV pair.  All syncs well but when the password is changed in vault (without changing secret name, etc), it does not reflect the update on the cluster. Possibly this is my own fault but it doesn't seem to be retrieving the most recent update from vault?

**Comment by werne2j** [comment]
Similar questione here https://github.com/IBM/argocd-vault-plugin/issues/173 the short version is you’ll need to hard refresh the Argo CD app to get the new value

**Comment by pbmoses** [comment]
thank you. I thought I searched closed issues as well but apparently not. The prompt reply is much appreciated!
