### ISSUE TITLE
Add versioning to the docs

### ISSUE THREAD

**Issue by werne2j** [IBM/argocd-vault-plugin#194]
As we start to add more features and release new versions, we should version the docs so that users can find docs for the particular version they are using. 

Couple different ways to do it:
mkdocs with mike - https://github.com/squidfunk/mkdocs-material-example-versioning
mkdocs with readthedocs - https://docs.readthedocs.io/en/stable/versions.html

**Comment by jkayani** [comment]
Works and includes a banner message if someone is browsing the `main` docs: https://ibm.github.io/argocd-vault-plugin/main/
