### ISSUE TITLE
Remove `data` from vault paths

### ISSUE THREAD

**Issue by jhoover4** [IBM/argocd-vault-plugin#203]
**Is your feature request related to a problem? Please describe.**
I know this is required by the Vault API, but it seems like a case of leaky abstraction. I think we should hide this detail from users, i.e. have them only have to use the vault path they're familiar with without the `data`.

Its a small issue, but its one less thing for the users to remember/deal with!

I'd be willing to open a PR for this, but wanted to run it by y'all first.

**Describe the solution you'd like**
When referencing a vault path, no need to include `data` in the path

**Describe alternatives you've considered**
N/A

**Additional context**
Not sure if there's a reason we'd have to keep this?

**Comment by jkayani** [comment]
Hi, thanks for the suggestion! 

I do agree that it's a very specific detail that can be easily overlooked to someone new with these tools (ArgoCD, Hashicorp Vault, AVP). However, the plugin does take care to print a hopefully-helpful error message when it detects a KV-V2 Vault with the wrong path given:

<img width="1346" alt="Screen Shot 2021-09-10 at 13 08 28" src="https://user-images.githubusercontent.com/7196382/132891450-aa3a5716-2936-4f83-ba52-e914918d7c34.png">

> The Vault path: secret/nginx is empty - did you forget to include /data/ in the Vault path for kv-v2?

But maybe this isn't enough, or the error message can be revised in some way. 

It also looks like the docs don't call out this detail which would be good to have. If there is more interest in this we can def. do it.

**Comment by jkayani** [comment]
As for implementing this feature, I don't see any reason it couldn't be done in a backwards-compatible way. Something like:

```
if kv-v2
  if path includes /data/
    use it
  else
    inject /data in the right place
```

Again, if there's sufficient interest, it can be done

**Comment by jhoover4** [comment]
Yeah I've seen the error message before which is definitely helpful! I was just thinking it might be better to not have to have users worry/care about it at all.

But ah I see, that's a bummer :/. Would you be able to make a call to vault to figure out the path or something? If its too complicated though no worries

**Comment by jkayani** [comment]
There is a CLI command https://www.vaultproject.io/docs/commands/secrets/list#secrets-list for that but I don't know the REST endpoint equivalent. And even if there was one, what if there are _multiple_ KV-V2 engines enabled at different paths in a given instance (like a multi-tenant instance)? How would we choose the right one?
