### ISSUE TITLE
Over-sanitized yaml output

### ISSUE THREAD

**Issue by RomanBats** [IBM/argocd-vault-plugin#212]
**Describe the bug**
It seems to me that after running argocd-vault-plugin for a YAML that has comments and quotes -  most quotes and all comments are removed, properties are reordered.

Is there a way to control this behavior?

Please, see a screenshot below of two outputs comparison - left is output from 'helm template', right - output from the plugin after 'helm template'.

**To Reproduce**
1. run argocd-vault-plugin for yaml with comments and quotes

**Expected behavior**
Only secrets are injected without any other modification to source YAML

**Screenshots**
![image](https://user-images.githubusercontent.com/5024978/135486593-a01cc53f-e2b2-4093-9631-0e8087724f6a.png)

**Additional context**

**Comment by werne2j** [comment]
Hi @RomanBats the way the yaml outputs is expected as it is i Kubernetes compliant format. We run the yamls through the same mechanism that `kubectl apply` and Argo CD use. At the end of the day the order should not matter. So we are going to consider this a `wontfix`. Thanks for your question!

**Comment by RomanBats** [comment]
@werne2j, thanks for explanation!
