### ISSUE TITLE
Multi-Tenant Capability? 

### ISSUE THREAD

**Issue by flickerfly** [IBM/argocd-vault-plugin#229]
**Is your feature request related to a problem? Please describe.**
I'm operating a multi-tenant ArgoCD instance. Currently, we don't have an effective way to allow Application developers to include secrets into their Kustomize code processed by ArgoCD. As a solution for this, we're evaluating Hashicorp Vault and this appears to be a part of that solution, but does not appear to support multi-tenant scenarios. I'm concerned that if I used this, any tenant would be able to access any other tenant's Vault contents.

**Describe the solution you'd like**
I'd like to provide a Vault configuration on a Project or Application level that would restrict users of ArgoCD from having the credentials to view other users Vault contents. 

**Describe alternatives you've considered**
I've considered running ArgoCD instances per project or application, but that's a significant increase of resource consumption both in daily usage and maintenance.

**Comment by werne2j** [comment]
This conversation in this issue https://github.com/IBM/argocd-vault-plugin/issues/230 should solve your multi tenancy question
