### ISSUE TITLE
Extra modifiers

### ISSUE THREAD

**Issue by denraf** [IBM/argocd-vault-plugin#232]
**Is your feature request related to a problem? Please describe.**
We upload a base64 encoded yaml file into our vault. When retrieving this file with the plugin, we need to be able to base64 decode it and parse it so we can get a specific value out of the yaml file.

**Describe the solution you'd like**
2 extra modifiers:
- base64decode
- yamltojson

**Comment by werne2j** [comment]
Those will be great additions, thanks @denraf!

**Comment by werne2j** [comment]
These modifiers were released in https://github.com/IBM/argocd-vault-plugin/releases/tag/v1.6.0
