### ISSUE TITLE
Misleading inline-path documentation

### ISSUE THREAD

**Issue by MoskitoHero** [IBM/argocd-vault-plugin#238]
Hello,

I am trying to implement the plugin with my Helm chart and Google Secrets Manager, but I found the documentation about inline-paths in the "How it works" to be misleading:

https://github.com/IBM/argocd-vault-plugin/blob/2485527b1cf0560a860b0e0d1bfba873023ebeff/v1.5.0/howitworks/index.html#L951 tells me that the path should look like `<path:some/path#secret-key>` but https://github.com/IBM/argocd-vault-plugin/blob/7faaabd85a0302ac5cc86871a51a0401efd15a09/pkg/backends/gcpsecretmanager.go#L43 raises an error if I don't use a path with slashes like `<path:some/path/secret-key>`.

If this is a Google Secrets Manager specificity, the documentation should mention it. I could make a PR if needed.

**Comment by werne2j** [comment]
@MoskitoHero The documentation for the GCP backend describes the necessary inline path format https://ibm.github.io/argocd-vault-plugin/v1.5.0/backends/#gcp-secret-manager

**Comment by MoskitoHero** [comment]
Thanks for your reply. Yes, I just saw that this morning.

While I understand that the "How it Works" page cannot mention all the backend-related configurations, it would be nice to have a link to the "Backends" page near these examples. IMHO this would make things a bit clearer.
