### ISSUE TITLE
usage example

### ISSUE THREAD

**Issue by 99** [IBM/argocd-vault-plugin#27]
**Is your feature request related to a problem? Please describe.**
Hi,
This is more like a documentation request. 

I'm trying to use this plugin with Vault and ArgoCD using K8s `Secret`
Currently after installing it i'm not sure it works as expected. (I'm new to ArgoCD)

My setup:  I'm trying to deploy helm chart and I'm storing overrides file(with sensitive secrets) in my Vault.

**Describe the solution you'd like**
The repo with usage example would be nice to have. Thank you.

Update: maybe a short blog/doc/readme (I can write one as well), but so far I can't make it work with my setup.

**Comment by werne2j** [comment]
Thanks for the interest @99 hope to have the docs updated very soon! Will let you know when we do

**Comment by werne2j** [comment]
@99 we have added some new documentation, hopefully that will help get you started!
