### ISSUE TITLE
Use token if still valid

### ISSUE THREAD

**Issue by werne2j** [IBM/argocd-vault-plugin#31]
Right now we get a new token everytime the tool is called. We should store the token and check if its still valid and using that if it is still valid before trying to get a new token

**Comment by werne2j** [comment]
Will have to write to a file, not able to store the value as a env var. Wondering if we can use the same config file for the token and the required params. Or even if this work is truly necessary.

**Comment by jkayani** [comment]
Using this https://github.com/spf13/viper#writing-config-files along with `viper.Set("VAULT_TOKEN", token)` could help
