### ISSUE TITLE
[Q] Updating secrets

### ISSUE THREAD

**Issue by wrdls** [IBM/argocd-vault-plugin#34]
Hi!

First of all, thank you for open-sourcing this, it looks promising.

I haven't used it yet, but I was wondering how updating secrets works? If you update the value in Vault, do you just press sync in ArgoCD to update the value in the Kubernetes secret?

**Comment by werne2j** [comment]
@wrdls Thanks for the question. So the way it works is, if you update the value in vault, you would then perform a `hard-refresh`, which would in turn run the plugin as a dry-run and then putting the kubernetes secret out of sync. Then  simple sync in ArgoCD would bring in the new value from Vault.

**Comment by wrdls** [comment]
Ok. Not ideal since the hard refresh button is bit hidden in the UI but probably sufficient.

Thanks for quick answer!

**Comment by werne2j** [comment]
You can also use the cli to run `argocd diff app_name --hard-refresh` via some sort of automation when vault gets updated. Which would automatically put the secret out of sync. Hope that helps!
