### ISSUE TITLE
Please can the plugin be made to work with .yml files as well as .yaml files

### ISSUE THREAD

**Issue by tim-sendible** [IBM/argocd-vault-plugin#44]
**Is your feature request related to a problem? Please describe.**
Because I'm lazy, I tend to call my files .yml instead of .yaml. This throws up the error: `no YAML files were found in ./`

**Describe the solution you'd like**
Given I have a file ending in .yml
When I run the plugin
Then the plugin pulls the secret(s) from vault

**Comment by jkayani** [comment]
This is very reasonable and should be doable - I too was lazy and wrote the code to just look for `.yaml` files :). Will try to roll out a fix soon

**Comment by werne2j** [comment]
Released in 0.3.0 https://github.com/IBM/argocd-vault-plugin/releases/tag/v0.3.0
