### ISSUE TITLE
Incorrect permissions when installing the plugin

### ISSUE THREAD

**Issue by tico24** [IBM/argocd-vault-plugin#45]
**Describe the bug**
The readme says to do the following:
```
 args:
    - wget -O argocd-vault-plugin
      https://github.com/IBM/argocd-vault-plugin/releases/download/v0.1.0/argocd-vault-plugin_0.1.0_linux_amd64

      mv argocd-vault-plugin /custom-tools/
```

Firstly, this is not the latest version of the plugin.

Secondly, if one does this then the binary does not have execution permissions and users will get this when trying to manually execute on the argocd-repo-server

```
argocd@argocd-repo-server-7b44865f66-7pjhw:~$ argocd-vault-plugin --help
bash: /usr/local/bin/argocd-vault-plugin: Permission denied
```

As a workaround, I installed the plugin using this:
```
args:
  - wget -O argocd-vault-plugin
    https://github.com/IBM/argocd-vault-plugin/releases/download/v0.2.2/argocd-vault-plugin_0.2.2_linux_amd64
    
    chmod 755 argocd-vault-plugin && mv argocd-vault-plugin /custom-tools/
```

**To Reproduce**
1. Follow the readme
2. exec onto one of the argocd-repo-servers
3. Run the command: `argocd-vault-plugin --help`

**Expected behavior**
I should be able to follow the readme to install the plugin without error

**Comment by werne2j** [comment]
Updated the readme to include the step to chmod the binary
