### ISSUE TITLE
Confusing error messages when an incorrect vault path is used

### ISSUE THREAD

**Issue by tico24** [IBM/argocd-vault-plugin#47]
**Describe the bug**
I use Vault kv-v2, and in order to access a secret using the api you have to put /data/ in the path.

There are two bugs here:
1. It would be nice for this documentation to remind users of that.
2. If you get the path wrong and vault sends a 404, the resulting error message is confusing.

**To Reproduce**
1. In vault, in a KV v2 Secrets Engine, do a `vault kv put example/path/and exampleKey=123`
2. Retrieve that key using `vault kv get -field=exampleKey example/path/and`
3. Vault will return `123`
4. Set up a test yaml file and set the avp_path annotation to match what you just tested. eg: `avp_path: example/path/and`
5. When you run the plugin, you will get the following error:

`Replace: could not replace all placeholders in SecretTemplate data: [replaceString: missing Vault value for placeholder username in string sample-secret: <exampleKey>]`

What has **actually** happened is that Vault has returned a 404 on that path... but the user is not aware of this, especially as the vault kv get command works.

The fix for this is to change the avp_path value to be:

`avp_path: example/data/path/and`

**Expected behavior**
The user should be told when Vault returns a 404 to the whole path. Currently the user thinks that the issue lies purely with the key itself.

**Comment by jkayani** [comment]
Good news -  I think the answer to this is as simple as checking for an empty map of Vault data before doing the replacements, and returning an error and doing nothing (since nothing can be replaced). 

I'll give that fix a try at some point soon and see if it works out

**Comment by werne2j** [comment]
Released in 0.3.0 https://github.com/IBM/argocd-vault-plugin/releases/tag/v0.3.0
