### ISSUE TITLE
Add vault kubernetes auth method

### ISSUE THREAD

**Issue by r0bj** [IBM/argocd-vault-plugin#50]
**Describe the solution you'd like**
It would be useful to add Kubernetes Auth Method (https://www.vaultproject.io/docs/auth/kubernetes) as an alternative to AppRole Auth Method. It's much easier to use if particular k8s cluster is already configured in Vault - instead of providing `Vault AppRole Role_ID` and `Vault AppRole Secret_ID` just use existing ServiceAccount.

**Comment by werne2j** [comment]
Thanks for the suggestion @r0bj we will look into this. We are open to accepting contributions if that is something you would be interested in. Otherwise we will add to our backlog!

**Comment by werne2j** [comment]
Support has been merged to main. Will be released with version 0.5.0 in the coming days

**Comment by werne2j** [comment]
Kubernetes auth support now available in https://github.com/IBM/argocd-vault-plugin/releases/tag/v0.5.0
