### ISSUE TITLE
Unable to register the plugin , following the steps of adding the configManagementPlugins

### ISSUE THREAD

**Issue by clcchai** [IBM/argocd-vault-plugin#57]
**Describe the bug**
unable to register the argocd-vault-plugin and didnt show up on the ui
**To Reproduce**
1. plugin was installed successfully to argocd - repo server via the init container
2. however, following on from that, try to add the configuration management plugin to the argocd-cm 
3. unable to see the plugin registered on argoCD

if we shell into the repo-server pod, following what the configuration management plugin tries to perform, as below
generate command will not yield anything as it expects yaml files to generate manifest

repo-server-65fb95bfc8-hk92g:~$ argocd-vault-plugin generate ./
Error: Must provide a supported Vault Type
Usage:
  argocd-vault generate <path> [flags]

Flags:
  -c, --config-path string   path to a file containing Vault configuration (YAML, JSON, envfile) to use
  -h, --help                 help for generate
  -s, --secret-name string   name of a Kubernetes Secret containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD)

Must provide a supported Vault Type

**Expected behavior**
expect the plugin registered and displayed at argoCDUI

**Comment by werne2j** [comment]
Can you share your `argoocd-cm`?

Also, that error `Must provide a supported Vault Type` is because you have not provided the necessary configuration https://github.com/IBM/argocd-vault-plugin#configuration

**Comment by clcchai** [comment]
argocd-cm -o yaml
apiVersion: v1
data:
  configManagementPlugins: |-
    - name: argocd-vault-plugin
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
  dex.config: |-
    connectors:

so the question I have is - do we need a secret prior to registering the plugin so that the plugin will show up on the argoCD UI?
just want very clear when I read the doc and also the blog you have:
https://itnext.io/argocd-secret-management-with-argocd-vault-plugin-539f104aff05

**Comment by werne2j** [comment]
The config map looks good. You dont need the secret before hand, that was just why you were seeing the error. One reason you may not be seeing the plugin registered is if you didnt restart the `argocd-repo-server` deployment. So i would try deleting the `argocd-repo-server` pods, let them re-create and hopefully you will see the plugin in the UI.

**Comment by clcchai** [comment]
Oh, I didnt see the error, it is just me trying to exec into the repo-server pod and follow the config map directive in running the generate command.
I did restart the repo-server pod multiple times and when I logged in to the argocd console/ui, I just cant figure out what the changes are, obviously I am not seeing the plugin shown up.

**Comment by werne2j** [comment]
Interesting, that should be all you need to do. You can see the ArgoCD docs right here https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#plugins. So if the binary exists (which it seems like it does). You just have to tell ArgoCD what command to run via `argocd-cm` which it seems you have done.

In the UI you are going to `New App` and then scrolling down to where it it has a dropdown that says `Directory` and selecting `Plugin`?

<img width="243" alt="Screen Shot 2021-02-09 at 3 58 24 PM" src="https://user-images.githubusercontent.com/5973248/107427648-a604ea00-6aef-11eb-9bc0-d4da4552175e.png">

**Comment by clcchai** [comment]
![Screen Shot 2021-02-10 at 8 02 39 am](https://user-images.githubusercontent.com/4087822/107428187-6208f800-6b76-11eb-9a6f-97010087076b.png)

**Comment by clcchai** [comment]
its shown up as blank
def I have the argocd-vault-plugin in my repo-serverr pod
$ oc rsh argo-cd-repo-server-65fb95bfc8-vbpvc
$ argocd-vault-plugin
This is a plugin to replace <wildcards> with Vault secrets

Usage:
  argocd-vault [flags]
  argocd-vault [command]

Available Commands:
  generate    Generate manifests from templates with Vault values
  help        Help about any command
  version     Print argocd-vault-plugin version information

Flags:
  -h, --help   help for argocd-vault

Use "argocd-vault [command] --help" for more information about a command.

**Comment by clcchai** [comment]
strangely , I checked my cm, its gone and I reapplied the argocd-cm again and now its magically appeared.
hmm... so if the argocd-server gets restarted ( as in the pod) is there a chance the argocd-cm gets overwritten back to original state?

**Comment by werne2j** [comment]
hmm i guess it depends on how you deployed argocd. Did you deploy using the argocd operator? If so, that would overwrite back to an original state

**Comment by clcchai** [comment]
yes via operator. hmm...so its not persisted if you restart the argo-server pod

**Comment by werne2j** [comment]
So you should be able to register the plugin via the operator https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#config-management-plugins and it wont overwrite the config map

**Comment by clcchai** [comment]
hey thanks for that above, looks like with operator, we need to pay attention to these things.

**Comment by werne2j** [comment]
No problem @clcchai glad you got it working
