### ISSUE TITLE
Update the README to explain configuration better

### ISSUE THREAD

**Issue by jkayani** [IBM/argocd-vault-plugin#60]
Instead of a giant table of env variables, let's do something like this: https://airflow.apache.org/docs/apache-airflow/1.10.12/security.html#google-authentication so that a user is given clear copy+paste'able examples of how to configure the plugin the way they need it

**Comment by werne2j** [comment]
Not sure how to explain the linking and unlinking of the PR ¯\_(ツ)_/¯
