### ISSUE TITLE
Add support for vault namespaces when configuring using a secret

### ISSUE THREAD

**Issue by sam-sla** [IBM/argocd-vault-plugin#68]
**Is your feature request related to a problem? Please describe.**
Our vault instance uses [namespaces](https://www.vaultproject.io/docs/enterprise/namespaces), and that needs to be set on every request to vault.

**Describe the solution you'd like**
The plugin should be able to read an extra var from the secret for the `VAULT_NAMESPACE` and pass it on each call to the vault instance.

**Describe alternatives you've considered**
There is a workaround to set `VAULT_NAMESPACE` as an env var inside the argocd-repo-server pod. But it's inconvenient to configure both a secret containing the configuration for the plugin (plus all the serviceaccount/role/rolebinding stuff), and still have to configure env vars for the pods.

**Comment by werne2j** [comment]
Hi @sam-sla thanks for the suggestion. We will look to get this request in as soon as we can. In the meantime feel free to add a contribution yourself! We can assign the issue to you if you would like

**Comment by sam-sla** [comment]
Thanks @werne2j for now I'll keep the workaround but I'll update this issue if I find time to work on this 👍

**Comment by werne2j** [comment]
@sam-sla PR #76 will add support for Namespaces

**Comment by sam-sla** [comment]
😄 Great! You guys are moving fast 💨

**Comment by werne2j** [comment]
Namespace support now available in https://github.com/IBM/argocd-vault-plugin/releases/tag/v0.5.0
