### ISSUE TITLE
Plugin find/replace logic 

### ISSUE THREAD

**Issue by jkayani** [IBM/argocd-vault-plugin#8]
Here's how this plugin needs to work, roughly:

- Accept a path in a Git repository to a collection of templated YAML files (where a file can have multiple manifests with `---` concatenation). We'll want the templated YAML we expect to be well-defined (so loading into a `struct`)

- Read each manifest, and perform a find/replace of Vault values based on the `Kind` (i.e, there may be 2 manifests with `<placeholder>` in them, but they should be replaced differently since they're from different kinds of resources. In other words, `placeholder`'s don't have to be unique across manifests for a given repo)

- Stream the resulting YAML back out for Argo to apply

Some assumptions:

- We're planning to allow users to supply a `path` annotation in their templated YAML, signifying the Vault path to find/replace from. For multiple kinds of resources, that might look like:

```
/foo/deployment => collection of key/value pairs to replace in a `kind: Deployment`
/foo/secret => collection of key/value pairs to replace in a `kind: Secret`
etc
```

Some design questions:

- How should `namespace: <namespace>` be handled? Most users will specify the namespace in the Argo Application CR like here: https://github.com/werne2j/argocd-example/blob/master/operations/templates/vault.yaml#L11

**Comment by werne2j** [comment]
For the question on the bottom, i think that we do not treat that any different then any other `<thing>` if within `foo/deployment` they have a `namespace` key we fill it in if not we dont.

**Comment by jkayani** [comment]
So far we have implemented:

- Deployment and Secret: #15 
- ConfigMap: #18 
- Service: #22 

The remaining ones on the immediate roadmap are:

- CronJob
- Job
- Ingress
