### ISSUE TITLE
getting an issue while using secrets object with deployment objects

### ISSUE THREAD

**Issue by anup1384** [IBM/argocd-vault-plugin#80]
I'm getting an issue while using secrets object with deployment objects.
repo >>
https://github.com/anup1384/arogcd-vault-demo.git
>>>
ComparisonError
rpc error: code = Unknown desc = Manifest generation error (cached): `argocd-vault-plugin generate ./` failed exit status 1: Error: Error making API request. URL: GET http://vault.abc.com/v1/deployment Code: 403. Errors: * permission denied Usage: argocd-vault generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD) Error making API request. URL: GET http://vault.abc.com/v1/deployment Code: 403. Errors: * permission denied
<<<

**Comment by werne2j** [comment]
Hi @anup1384, which version of the plugin are you using?

**Comment by anup1384** [comment]
@werne2j  plugin version is v0.2.2

**Comment by werne2j** [comment]
@anup1384 Please upgrade to at least `0.4.0`. This is an issue that was solved in https://github.com/IBM/argocd-vault-plugin/pull/62

**Comment by anup1384** [comment]
I have used 0.4.0 now and getting an error 
>>>
Unable to create application: application spec is invalid: InvalidSpecError: Unable to generate manifests in .: rpc error: code = Unknown desc = `argocd-vault-plugin generate ./` failed exit status 1: Error: Could not get data from Vault, check that kv-v2 is the correct engine Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD) Could not get data from Vault, check that kv-v2 is the correct engine
<<<

**Comment by werne2j** [comment]
@anup1384 If you look at the error, there is one of two things that could be happening..
1. You are using Kv 1 as the Vault secret engine and if that is the case you will either need to set the `KV_VERSION` environment variable or the `kv_version` annotation to be `1`. https://github.com/IBM/argocd-vault-plugin#full-list-of-supported-parameters
2. You are using Kv 2 and your path is wrong, which in that case may just need `data` to be included into your path `Insurance-DevOps/test/data/secrets` (A guess, as i don't know your vault structure)

**Comment by anup1384** [comment]
Thanks, @werne2j  
The path is correct and I'm using the KV 1 version.
I have added annotation in YAML . I have stored the key (testpass)at the path "Insurance-DevOps/test/secrets" in the vault.
```
kind: Secret
apiVersion: v1
metadata:
  name: test-secret
  namespace: default
  annotations:
    avp_path: "Insurance-DevOps/test/secrets"
    kv_version: 1
type: Opaque
data:
  test-secret: <testpass>
```
but still, I don't why getting a 403 error, I think the plugin is not fetching the correct vault path.

>>>

Unable to create application: application spec is invalid: InvalidSpecError: Unable to generate manifests in .: rpc error: code = Unknown desc = `argocd-vault-plugin generate ./` failed exit status 1: Error: Error making API request. URL: GET http://vault.abc.com/v1/secret Code: 403. Errors: * permission denied Usage: argocd-vault-plugin generate <path> [flags] Flags: -c, --config-path string path to a file containing Vault configuration (YAML, JSON, envfile) to use -h, --help help for generate -s, --secret-name string name of a Kubernetes Secret containing Vault configuration data in the argocd namespace of your ArgoCD host (Only available when used in ArgoCD) Error making API request. URL: GET http://vault.abc.com/v1/secret Code: 403. Errors: * permission denied
✖
<<<

**Comment by werne2j** [comment]
@anup1384 You must put quotes around the 1
```
kind: Secret
apiVersion: v1
metadata:
  name: test-secret
  namespace: default
  annotations:
    avp_path: "Insurance-DevOps/test/secrets"
    kv_version: "1"
type: Opaque
data:
  test-secret: <testpass>
  ```

**Comment by anup1384** [comment]
Yes After passing as list working now.
Thanks

**Comment by werne2j** [comment]
No problem, glad you got it to work! Will close this issue.
