### ISSUE TITLE
PATH_PREFIX deprecation 

### ISSUE THREAD

**Issue by werne2j** [IBM/argocd-vault-plugin#83]
We should look into deprecating the PATH_PREFIX as it seems to be a bit confusing and does not seem to get any usage. We can remove that as the default secret location and then force the annotation or allow paths as the secret value instead of just an annotation

**Comment by jkayani** [comment]
For v0.6.0 we may want to print a message saying this env var is deprecated

For v1.0.0 we will want to straight-up ignore this env var

**Comment by werne2j** [comment]
https://github.com/IBM/argocd-vault-plugin/pull/96 adds a print message for deprecating the env var
