### ISSUE TITLE
Vault secret changes awareness

### ISSUE THREAD

**Issue by yonahd** [IBM/argocd-vault-plugin#87]
Can the plugin regenerate the kubernetes secret if it detects a change in the secret in vault?
This would allow secrets to be completely dynamic.

**Comment by werne2j** [comment]
@yonahd If you change the value in Vault and then do a Hard Refresh in ArgoCD, you will see the secret becomes out of sync as it becomes aware of the new value. Then all you have to do is resync your ArgoCD app and you will get the new value

**Comment by yonahd** [comment]
@werne2j Amazing! wasn't aware of the hard refresh ability.
