### ISSUE TITLE
There is no way to read data already base64 encoded from vault

### ISSUE THREAD

**Issue by sam-sla** [IBM/argocd-vault-plugin#92]
**Describe the bug**
The plugin seems to always encode the data read from vault when specified in the `data` key, because according to the specification that's how the data should be passed into the secret ([reference](https://kubernetes.io/docs/concepts/configuration/secret/#overview-of-secrets)). To pass string data without encoding, the secret accepts a `stringData` key which the plugin does not encode and pass as-is. The problem then is that there is no way to read data already encoded in base64 from vault, because if we use `stringData` Kubernetes expects it to not be encoded, and if we use `data` the plugin encodes the already encoded data that is read from vault, resulting in invalid "double" base64 encoded data inside the secret in Kubernetes.

**To Reproduce**
1. Add some base64 encoded data/string in a vault path
2. Reference that secret using the `data` key in the secret
3. Get the secret object as yaml from k8s and check that the data key contains double encoded data, i.e. the secret is not valid.

**Expected behavior**
I expect the key `data` to accept already encoded data from vault. I understand that this might cause confusion to users, but IMHO it seems correct to assume that if we are reading non-encoded data from vault, we should use the key `stringData`?

**Additional context**
Maybe this was a conscious UX decision, as the users will reference string secrets in vault and want them encoded into the `data` key inside the secret in vault. Perhaps we can have a flag to run the plugin in a special mode that expects already base64 encoded data when its provided in the key `data`, therefore not encoding the values read from vault (already encoded) ?

**Comment by jkayani** [comment]
Hi,

You're absolutely right! The plugin assumes that all data is stored in Vault in plain-text, nothing base64'd. So for your case that's a problem. We can probably accommodate this use-case via a command line flag or some other configuration option. 

> but IMHO it seems correct to assume that if we are reading non-encoded data from vault, we should use the key stringData?

Technically this all up to how the YAML is written. If the YAML says this:
```
data:
  THING: <thing>
```
then the plugin will base64 the Vault data before replacing the placeholder. But if it says:
```
stringData:
   THING: <thing>
```
it will replace the placeholder with the data from Vault as-is. So the plugin shouldn't make any assumptions at all here.

Anyway, we'll keep you updated on this and fix this sometime in the near future - feel free to leave additional feedback if you have any. I think your suggestion is pretty solid as-is. 

Thanks for the feedback!

**Comment by adit0012m** [comment]
@jkayani I should Thank everyone for the wonderful work.

We are expecting something similar. Describing few challenges as per my understanding and testing.

Tested the for both use cases,
```data:
          THING: <mykey>
``` 
The plugin does replace `data` key from Vault as-is ( but, Ref: then the plugin will base64 the Vault data before replacing the placeholder..). In our case, not the correct behaviour then.
and
```stringData:
          THING: <mykey>
```
Expected `stringData` inside the key should replace value from Vault as-is which is not working.

Configured yaml file looks as below:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  annotations:
    avp_path: <kv/data/secret-folder>
type: Opaque
data:
  MyKey: <MyKey>
```
Thoughts on this.

**Expecting a new Feature or an Existing Options are not Aware**
The plugin works perfectly fine with the plain text stored in Vault get's the value back in to the secret. Is there a way we can decode values present in a Vault secret path are encoded in the `base64` format at the secret end. This helps us to store certificate formats such as .crt, .pem etc...

* Store certificates in `base64` encoded format in Vault secret path and values are decoded when retrieves it from Vault server. Just to give an example. Same is achieved using Consul Template to render the Vault secret with side car container Vault k8s auth method.

Ex: ```{{with secret "secret/example"}} MyKey = {{.Data.data.MyKeyCerts | base64Decode}}{{end}}

So, is there any way we can decode base64 format data before it replaces the placeholder with the actual value --> something like "<base64decode MyKey>".

**Comment by werne2j** [comment]
After some discussion, what @jkayani and I are thinking is to remove the base64 encoding that happens on the fly and make assumptions that if you want to store base64d values in Vault you can use `data` and if you want to store plain text in Vault you would then use `stringData`.

This way the plugin isn't responsible for any transformation of data in flight.

@sam-sla what are your thoughts on that?

**Comment by sam-sla** [comment]
Thanks @werne2j and @jkayani for again having such a quick look at this :) And like @adit0012m said, thank you for the wonderful work you guys have been putting into this!

It looks like Adit has the same expectations as I did regarding passing a secret already base64 encoded into the `data` key. Our use case was also a certificate, more concretely a certificate bundle as a binary file that has to be base64 encoded in vault, and we couldn't get it to work with the plugin unfortunately.

I think it would be clear and well within reason to adopt the proposed changes! The plugin would not do any transformation and the users would be responsible to either pass data from vault already encoded into `data`, or as plain text into `stringData`. A clear description in the documentation shouldn't leave any doubts, but existing users would face breaking changes when upgrading a version of the plugin.

**Comment by werne2j** [comment]
Changes now available in https://github.com/IBM/argocd-vault-plugin/releases/tag/v0.6.0

**Comment by sam-sla** [comment]
Thanks a lot!
