### ISSUE TITLE
Timeout when calling the /login endpoint on vault api

### ISSUE THREAD

**Issue by khetanir** [IBM/argocd-vault-plugin#97]
**Describe the bug**
We are using the plugin to connect to IBM Secrets manager and noticed that the plugin was having http timeout failures when attempting to making a PUT request to auth/ibmcloud/login. `Put "<IBM_VAULT_URL>/v1/auth/ibmcloud/login": net/http: request canceled (Client.Timeout exceeded while awaiting headers)`

When testing those requests it seems the request regularly takes >10s and the DefaultHttpClient use by the VaultClient has a timeout of 10s, which is causing the timeouts I believe.

Having spoken to @werne2j, it seems the Vault default timeout is actually 60s, and the plan is to use the default hashicorp httpclient at some point - I propose in the interim the solution is to increase the timeout to 60s to match the default client.

**To Reproduce**
Run `argocd-vault-plugin generate` against a yaml, whilst configured for the IBM Secrets manager.

**Expected behavior**
Command to run successfully and replace the placeholders with password values

**Screenshots**

**Additional context**

**Comment by werne2j** [comment]
Change now available in https://github.com/IBM/argocd-vault-plugin/releases/tag/v0.6.0
